In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
df = pd.read_csv('Weather Data.csv')

In [3]:
df.head()

Day  Average temperature °F  Average humidity %  \
0  01-01-2009                    37.8                  35   
1  01-02-2009                    43.2                  32   
2  01-03-2009                    25.7                  60   
3  01-04-2009                     9.3                  67   
4  01-05-2009                    23.5                  30   

   Average dewpoint °F  Average barometer in.  Average windspeed mph  \
0                 12.7                   29.7                   26.4   
1                 14.7                   29.5                   12.8   
2                 12.7                   29.7                    8.3   
3                  0.1                   30.4                    2.9   
4                  5.3                   29.9                   16.7   

   Average gustspeed mph  Average direction (WNW)  Rainfall for month in.  \
0                   36.8                      274                     0.0   
1                   18.0                      240                     0.0   
2                   12.2                      290                     0.0   
3                    4.5                       47                     0.0   
4                   23.1                      265                     0.0   

   Rainfall for year in.  Maximum rain per minute in.   \
0                    0.0                           0.0   
1                    0.0                           0.0   
2                    0.0                           0.0   
3                    0.0                           0.0   
4                    0.0                           0.0   

   Maximum temperature °F   Minimum temperature °F   Maximum humidity %  \
0                     40.1                     34.5                  44   
1                     52.8                     37.5                  43   
2                     41.2                      6.7                  89   
3                     19.4                      0.0                  79   
4                     30.3                     15.1                  56   

   Minimum humidity %  Maximum pressure  Minimum pressure  \
0                  27            29.762            29.596   
1                  16            29.669            29.268   
2                  35            30.232            29.260   
3                  35            30.566            30.227   
4                  13            30.233            29.568   

   Maximum windspeed mph  Maximum gust speed mph  Maximum heat index °F  
0                   41.4                    59.0                   40.1  
1                   35.7                    51.0                   52.8  
2                   25.3                    38.0                   41.2  
3                   12.7                    20.0                   32.0  
4                   38.0                    53.0                   32.0

In [13]:
stats.iqr(df['Average dewpoint °F'], rng=(25,75))

23.150000000000006

In [14]:
np.percentile(df['Average temperature °F'], 50, interpolation='lower')

45.9

In [8]:
df.columns.is_numeric()

False

In [15]:
percentile_list = np.percentile(df['Average gustspeed mph'], [25,75])

In [16]:
type(percentile_list)

numpy.ndarray

In [17]:
percentile_list

array([ 4.4, 12.1])

In [21]:
mode_d = np.mod(df['Average gustspeed mph'])

TypeError: ufunc() missing 1 of 2required positional argument(s)

In [24]:
print(mode_d[0][0])

0.0


In [59]:
data = np.array([5390, 5993, 3097, 4796, 2236, 8678, 1840, 6760, 1682, 5814,5814, 3097,1682])

In [61]:
mean_d = round(np.mean(data),2)
median_d = np.median(data)
mode_d = stats.mode(data)[0][0]
percentile_list = np.percentile(data, [25,75], interpolation='lower')
iqr_d = stats.iqr(data, rng=(25,75), interpolation='lower')
skew_d = stats.skew(data)
kurtosis_d = stats.kurtosis(data)
print(data)
print(mean_d, median_d, mode_d, percentile_list, iqr_d, skew_d, kurtosis_d)

[5390 5993 3097 4796 2236 8678 1840 6760 1682 5814 5814 3097 1682]
4375.31 4796.0 1682 [2236 5814] 3578 0.26666274814139673 -1.0244168861066165


In [73]:
print(np.random.randn(100))

[-1.24100434e-01  5.44008709e-01  7.81009855e-01  1.99324485e+00
  5.60243233e-01  9.74746558e-01 -3.20475349e-01 -1.11478347e-01
  4.49758319e-01 -9.01977991e-01 -9.74353378e-01  7.65499449e-01
  6.34725566e-01 -1.27871361e+00 -6.36967346e-01  1.65661704e-01
 -8.27955790e-01  7.53441176e-01  3.90678344e-01  1.56335676e+00
  4.85534405e-01  1.25940490e+00  9.07425754e-01  1.72351109e-01
  2.96901797e-01  2.05195977e-01 -3.23233013e-03  3.20370881e-01
 -1.45688517e-01  9.74686642e-02 -6.24558806e-01  4.53763811e-01
 -6.42336055e-01 -2.59372613e-01 -3.41117873e-01  1.50700256e+00
 -7.24188578e-02  8.47855596e-01  4.44645574e-01  1.17367614e+00
  1.77391148e-02 -4.68919113e-01 -1.53578837e+00 -5.76242068e-01
 -1.03300948e-01  5.48512300e-01 -5.81225626e-01  1.12621205e+00
 -3.27535293e-01 -6.55909114e-02  1.96092442e+00  2.09862189e+00
 -6.12788862e-01 -9.71883441e-01  2.03724018e+00  9.70524271e-01
  6.84660518e-02 -5.34198595e-01 -9.67569082e-01  1.01036745e+00
 -4.33026119e-01 -3.02924

In [68]:
print(np.random.choice([11, 22, 33], 2, replace=False))

[33 11]


In [60]:
print(stats.mode(data))

ModeResult(mode=array([1682]), count=array([2]))


In [46]:
type(stats.mode(data))

scipy.stats.stats.ModeResult

In [78]:
data.

array([5390, 5993, 3097, 4796, 2236, 8678, 1840, 6760, 1682, 5814, 5814,
       3097, 1682])

In [84]:
np.random.seed(1)
dist = 47 + 9.971848109388686*np.random.randn(100)
num = abs(np.mean(dist) - 47)
print(num) 

0.6041229989324322


50.0

In [104]:
head

4927

In [131]:
sample = stats.binom.rvs(p=0.5, n=1, size= 1000, random_state=1)
type(sample)

numpy.ndarray

In [155]:
sample

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,

In [174]:
sample.apply(lambda x : x==0)

AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [172]:
l = [i for i in sample if i==0]

In [173]:
len(l)

494

In [175]:
s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))

In [176]:
'b' in s

True

In [177]:
s

a    89.2
b    76.4
c    98.2
d    75.9
dtype: float64

In [178]:
pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')

DatetimeIndex(['2017-09-11', '2017-09-13', '2017-09-15', '2017-09-17'], dtype='datetime64[ns]', freq='2D')

In [179]:
df = pd.DataFrame(np.arange(10), index=[ 'r1', 'r2', 'r3', 'row4', 'row5', 'row6', 'r7', 'r8', 'r9', 'row10'])

In [190]:
 g = df.groupby(df.index.str.len())
g.filter(lambda x: len(x)>= 1)

0
r1     0
r2     1
r3     2
row4   3
row5   4
row6   5
r7     6
r8     7
r9     8
row10  9

In [182]:
 df.groupby(df.index.str.len())

In [185]:
g.describe()

0                                          
  count mean       std  min   25%  50%   75%  max
2   6.0  4.0  3.405877  0.0  1.25  4.0  6.75  8.0
4   3.0  4.0  1.000000  3.0  3.50  4.0  4.50  5.0
5   1.0  9.0       NaN  9.0  9.00  9.0  9.00  9.0

In [198]:
df.iloc[:2]

0
r1  0
r2  1

In [209]:
df[:2]

0
r1  0
r2  1

In [214]:
pd.DESCR(df)

AttributeError: module 'pandas' has no attribute 'DESCR'

In [215]:
from sklearn import datasets

iris = datasets.load_iris()

In [216]:
type(iris)

sklearn.utils.Bunch

In [218]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [226]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [229]:
import sklearn.preprocessing as preprocessing

x = [[0, 0], [0, 1], [1,0]]
enc = preprocessing.OneHotEncoder()
print(enc.fit(x).transform([[0, 1]]).toarray())

[[1. 0. 0. 1.]]


In [232]:
import sklearn.preprocessing as preprocessing

regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
print(preprocessing.LabelEncoder().fit(regions).transform(regions))

[1 0 3 1 2 0]


In [259]:
def isHappy(n):
    dic = [2,3,4,5]
    sum = 0
    if n==1:
        return 1
    if n==0:
        return 0
    while(n!=1):
        num= str(n)
        for i in num:
            sum = sum + int(i)**2
        if sum in dic:
            return 0 
        if sum >1:
            n = sum
            dic.append(sum)
            sum = 0    
        else:
            return 1 

In [280]:
arr = np.array('123'.split())
arr

array(['123'], dtype='<U3')

In [277]:
'abc'.split()

['abc']

In [320]:
for i in range(26):
    if isHappy(i):
        print(i)

1
7
10
13
19
23


In [ ]:
7 > 49 >16 + 81 > 97 > 81 + 49 > 130 > 1 +9 +0> 10 > 1 + 0> 1

2 > 4 >16> 37 > 58 >89 > 145 >  42 > 20 > 4 >

5 >25 > 29 > 85 > 89 

In [327]:
dt = {0:False, 1:True, 4:False}
def isHappy(num):
    if num in dt:
        return dt[num]
    else:
        sum = 0
        for i in str(num):
            sum = sum +int(i)**2    
        value = isHappy(sum)
        dt[num]=value
        return value
    
arr = np.arange(1,26).reshape(5,5)
arr2 = []
n=len(arr)
for i in range(n-2):
    for j in range(n-2):     
        arr2.append(arr[i:i+3,j:j+3].flatten())
count1 =[]
for i in range(len(arr2)):
    count = 0
    for j in range(len(arr2[i])):
        if isHappy(arr2[i][j]):
            count = count+1
    count1.append(count)

for i in range(len(count1)):
    if count1[i]==np.max(count1):
        print(arr2[i].reshape(3,3))

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[12 13 14]
 [17 18 19]
 [22 23 24]]
[[13 14 15]
 [18 19 20]
 [23 24 25]]


In [286]:
arr = np.arange(1,26).reshape(5,5)

In [324]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [307]:
arr2 = []
n=len(arr)
for i in range(n-2):
    for j in range(n-2):     
        arr2.append(arr[i:i+3,j:j+3].flatten())

In [323]:
count1 =[]
for i in range(len(arr2)):
    count = 0
    for j in range(len(arr2[i])):
        if isHappy(arr2[i][j]):
            count = count+1
    count1.append(count)

for i in range(len(count1)):
    if count1[i]==np.max(count1):
        print(arr2[i].reshape(3,3))

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[12 13 14]
 [17 18 19]
 [22 23 24]]
[[13 14 15]
 [18 19 20]
 [23 24 25]]


In [321]:
print(count1)

[3, 2, 2, 2, 3, 3, 2, 3, 3]


In [336]:
n = [1,2,4,6]

In [337]:
n1 = np.arange(1,7)

In [338]:
n.sort()

In [339]:
def difference(n,n1):
    l1 = []
    for i in n1:
        if i not in n:
            l1.append(i)
    return l1

In [340]:
difference(n,n1)

[3, 5]

In [342]:
l1=[]
for i in range(1,7):
    if i not in n:
            l1.append(i)
print(l1)

[3, 5]


In [343]:
#Coding Question 3


In [402]:
arr = np.arange(1,10).reshape(3,3)

In [403]:
arr[0][0]=100

In [404]:
res1=arr.diagonal().sum()
res2=np.fliplr(arr).diagonal().sum()

In [405]:
sum1=0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i ==j:
            sum1 = sum1 + arr[i][j]

sum1   

114

In [406]:
n=len(arr)
sum=0
for i in range(n):
    for j in range(n,-1,-1):
        if ((i+j)==n-1):
            sum= sum+arr[i][j]
sum

15

In [407]:
print(res1,res2,sum1,sum)

114 15 114 15


In [408]:
arr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [448]:

str='mama'
str1=str[-1]+str[:-1]
str2=str[1:]+str[0]

In [449]:
if str2==str1:
    print("Doraemon M")

Doraemon M


In [437]:
str1

'amam'

In [438]:
str2

'amam'

In [452]:
str1 = 'Technoname10'
num =""
for i in str1:
    if i.isnumeric():
        num = num + i
if (len(str1) - len(num) -int(num)) == 0:
    print("Doraemon M")

Doraemon M
